<div class="grid_12">
    <div class="module">
        <h2><span>Detalhes</span></h2>
        <h1 class="titulo_sohw" >Detalhes</h1>
        <?php if ($this->usuario): ?>
            <dl class="detalhe">
                <dt class="detalhe">ID</dt>
                <dd class="detalhe"><?php echo $this->usuario->id; ?></dd>

                <dt class="detalhe">Usu&aacute;rio</dt>
                <dd class="detalhe"><?php echo $this->usuario->username; ?></dd>
                
                <dt class="detalhe">Role</dt>
                <dd class="detalhe"><?php echo $this->usuario->role; ?></dd>
                
                
                <dt class="detalhe">Opciones</dt>
                <dd class="detalhe">
                    <a href="<?php echo $this->url(array('controller' => 'Administrador', 'action' => 'menu'), null, true); ?>">Inicio</a>
                    |
                    <a href="<?php echo $this->url(array('controller' => 'usuario', 'action' => 'index'), null, true); ?>">Listar Usu&aacute;rios</a>
                    |
                    <?php echo $this->linkvoltar('voltar', 'back', 'voltar'); ?>
                </dd>

            </dl>
        <?php else: ?>
        <p><?php echo $this->message ?></p>
        <?php endif ?>
      </div> <!-- End .module -->
    <div style="clear:both;"></div>
 </div> <!-- End .grid_12 -->
<div style="clear:both;"></div>