<div class="grid_12">
    <div class="module">
        <h2><span>Detalles</span></h2>
        <h1 class="titulo_sohw" >Detalles</h1>
        <?php if ($this->red): ?>
            <dl class="detalhe">
                <dt class="detalhe">ID</dt>
                <dd class="detalhe"><?php echo $this->red->id; ?></dd>

                <dt class="detalhe">Rotulo</dt>
                <dd class="detalhe"><?php echo $this->red->rotulo; ?></dd>
                
                <dt class="detalhe">Link</dt>
                <dd class="detalhe"><?php echo $this->red->link; ?></dd>
                
                
                <dt class="detalhe">Opciones</dt>
                <dd class="detalhe">
                    <a href="<?php echo $this->url(array('controller' => ' Administrador ', 'action' => 'menu'), null, true); ?>">Inicio</a>
                    |
                    <a href="<?php echo $this->url(array('controller' => 'Red', 'action' => 'index'), null, true); ?>">Listar Redes Sociales</a>
                    |
                    <?php echo $this->linkvoltar('voltar', 'back', 'volver'); ?>
                </dd>

            </dl>
        <?php else: ?>
        <p><?php echo $this->message ?></p>
        <?php endif ?>
      </div> <!-- End .module -->
    <div style="clear:both;"></div>
 </div> <!-- End .grid_12 -->
<div style="clear:both;"></div>