<div style="float:left; width:342px; margin-right:7px; padding-top:10px;">

								<h1><a href="conteudo.php?tit=balanca_tem_deficit_de_us_952_milhoes_na_terceira_semana_de_novembro&id=84879" class="link2" title="Balança tem déficit de US$ 952 milhões na terceira semana de novembro">
								Balança tem déficit de US$ 952 milhões na terceira semana de novembro
								</a>
								</h1>
								<div class="linha"></div>
								<a href="conteudo.php?tit=galeria_casa_de_carnes_comercializa_100_kg_de_carne_suina_na_femix_2012&id=84878">
									 <div class="imagemHome1" style="background-image:url(imagens/n_2111_777712776.jpg)"></div>
								</a>
									<h6>Suínos</h6>
									<h2>
										<a href="conteudo.php?tit=galeria_casa_de_carnes_comercializa_100_kg_de_carne_suina_na_femix_2012&id=84878" class="link2" title="Galeria Casa de Carnes comercializa 100 Kg de carne suína na Femix 2012">
										Galeria Casa de Carnes comercializa 100 Kg de carne suína na Femix 2012
										</a>
										</h2>
									<div class="linha"></div>
										<a href="conteudo.php?tit=presidente_de_grupo_chines_diz_que_a_bahia_e_o_melhor_lugar_para_investir&id=84877">
									<div class="imagemHome1" style="background-image:url(imagem.php?w=300&h=150&imagem=n_2111_1132333189.jpg)"></div>
									</a>
									<h6>Bahia é o melhor lugar para investir</h6>
									<h2>
									<a href="conteudo.php?tit=presidente_de_grupo_chines_diz_que_a_bahia_e_o_melhor_lugar_para_investir&id=84877" class="link2" title="Presidente de grupo chinês diz que a Bahia é o melhor lugar para investir">
									Presidente de grupo chinês diz que a Bahia é o melhor lugar para investir
									</a>
									</h2>
									<div class="linha"></div>
									<a href="conteudo.php?tit=suinos_brasileiros_rumo_ao_japao&id=84876">
										<div class="imagemHome2" style="background-image:url(imagem.php?w=500&h=300&imagem=n_2111_776894847.jpg)"></div>
									</a>
									<h6>Suínos</h6>
									<h2>
									<a href="conteudo.php?tit=suinos_brasileiros_rumo_ao_japao&id=84876" class="link2" title="Suínos brasileiros rumo ao Japão">
									Suínos brasileiros rumo ao Japão
									</a>
									</h2>
									<div class="linha"></div>
									<a href="conteudo.php?tit=unesp_de_jaboticabal_recebe_simposio_de_qualidade_de_carne&id=84869">
											<div class="imagemHome1" style="background-image:url(imagem.php?w=300&h=150&imagem=n_2111_817034695.jpg)"></div>
									</a>
									<h6>Simpósio de Qualidade de Carne</h6>
									<h2><a href="conteudo.php?tit=unesp_de_jaboticabal_recebe_simposio_de_qualidade_de_carne&id=84869" class="link2" title="Unesp de Jaboticabal recebe Simpósio de Qualidade de Carne">
									Unesp de Jaboticabal recebe Simpósio de Qualidade de Carne
									</a>
									</h2>
									<div class="linha"></div>
									  <a href="conteudo.php?tit=por_que_eu_nao_travei_o_preco_da_soja&id=84868">
										<div class="imagemHome1" style="background-image:url(imagem.php?w=300&h=150&imagem=n_2111_208569652.gif)"></div>
									 </a>
									<h6>Análise de Mercado</h6>
									<h2><a href="conteudo.php?tit=por_que_eu_nao_travei_o_preco_da_soja&id=84868" class="link2" title="Por que eu não travei o preço da soja?">
									Por que eu não travei o preço da soja?
									</a>
									</h2>
									<div class="linha"></div>
									 <a href="conteudo.php?tit=precos_em_alta_indicam_melhora_na_venda_de_carne_bovina&id=84867">
										<div class="imagemHome1" style="background-image:url(imagem.php?w=300&h=150&imagem=n_2111_750176926.jpg)"></div>
									</a>
									<h6>Frigoríficos</h6>
									<h2><a href="conteudo.php?tit=precos_em_alta_indicam_melhora_na_venda_de_carne_bovina&id=84867" class="link2" title="Preços em alta indicam melhora na venda de carne bovina">
									Preços em alta indicam melhora na venda de carne bovina
									</a>
									</h2>
									<div class="linha"></div>
									<a href="conteudo.php?tit=df_mapa_busca_regularizar_vinhos_coloniais_no_brasil&id=84866">
										<div class="imagemHome2" style="background-image:url(imagem.php?w=500&h=300&imagem=n_2111_789666769.jpg)"></div>
									</a>
									<h6>Regularização de vinhos coloniais</h6>
									<h2><a href="conteudo.php?tit=df_mapa_busca_regularizar_vinhos_coloniais_no_brasil&id=84866" class="link2" title="DF: Mapa busca regularizar vinhos coloniais no Brasil">
									DF: Mapa busca regularizar vinhos coloniais no Brasil
									</a>
									</h2>
									<div class="linha"></div>
									<div style="width:170px; float:left; text-align:center">
									<a href="conteudo.php?tit=diretor_do_inss_promete_resolver_questao_das_aposentadorias_rurais&id=84865">
											<div class="imagemHome1" style="margin-left:15px; background-image:url(imagem.php?w=300&h=150&imagem=n_2111_570184160.jpg)"></div>
									</a>
									<h6>aposentadorias rurais</h6>
									<h2 style="font-size:12px"><a href="conteudo.php?tit=diretor_do_inss_promete_resolver_questao_das_aposentadorias_rurais&id=84865" class="link2" title="Diretor do INSS promete resolver questão das aposentadorias rurais">
									Diretor do INSS promete resolver questão das aposentadorias rurais</a></h2>
									</div>
									<div style="width:170px; float:left; text-align:center">
									 <a href="conteudo.php?tit=inflacao_em_sao_paulo_mantem_movimento_de_queda_e_fica_em_0,7_na_segunda_apuracao_de_novembro&id=84864">
										<div class="imagemHome1" style="margin-left:15px; background-image:url(imagem.php?w=300&h=150&imagem=n_2111_2014327448.jpg)"></div>
									</a>
									<h6>Economia</h6>
									<h2 style="font-size:12px"><a href="conteudo.php?tit=inflacao_em_sao_paulo_mantem_movimento_de_queda_e_fica_em_0,7_na_segunda_apuracao_de_novembro&id=84864" class="link2" title="Inflação em São Paulo mantém movimento de queda e fica em 0,7% na segunda apuração de novembro">
									Inflação em São Paulo mantém movimento de queda e fica em 0,7% na segunda apuração de novembro
									</a>
									</h2>
									</div>
									<div class="linha"></div>
									<div style="width:170px; float:left; text-align:center">
									<a href="conteudo.php?tit=carne_ovina_ganha_novos_preparos&id=84863">
										<div class="imagemHome1" style="margin-left:15px; background-image:url(imagem.php?w=300&h=150&imagem=n_2111_154670687.jpg)"></div>
									</a>
									<h6>Caprinos e ovinos</h6>
										<h2 style="font-size:12px"><a href="conteudo.php?tit=carne_ovina_ganha_novos_preparos&id=84863" class="link2" title="Carne ovina ganha novos preparos">
										Carne ovina ganha novos preparos
										</a>
										</h2>
									</div>
									<div style="width:170px; float:left; text-align:center">
									<a href="conteudo.php?tit=precos_do_boi_gordo_e_participacao_de_femeas_nos_abates&id=84862">
										<div class="imagemHome1" style="margin-left:15px; background-image:url(imagem.php?w=300&h=150&imagem=n_2111_1856027458.jpg)"></div>
									</a>
									<h6>Bovinos (corte)</h6>
										<h2 style="font-size:12px"><a href="conteudo.php?tit=precos_do_boi_gordo_e_participacao_de_femeas_nos_abates&id=84862" class="link2" title="Preços do boi gordo e participação de fêmeas nos abates">
										Preços do boi gordo e participação de fêmeas nos abates
										</a>
										</h2>
									</div>
						</div>
						
						<div style="float:left; width:303px; margin:0 6px;">
							
									<div id="navslide"></div>            
									<div id="cyclenews" style="overflow: hidden; height: 283px; width: 100%;">
												
										<div style="height:283px;">
											<a href="conteudo.php?tit=feira_nacional_da_agricultura_familiar_quer_estimular_negocios&id=84875"><div class="imagemHome3" style="background-image:url(imagem.php?w=600&h=400&imagem=n_2111_402676377.jpg)"></div></a>
											<h6>Agricultura familiar</h6>
											<h2><a href="conteudo.php?tit=feira_nacional_da_agricultura_familiar_quer_estimular_negocios&id=84875" class="link2" title="Feira Nacional da Agricultura Familiar quer estimular negócios">Feira Nacional da Agricultura Familiar quer estimular negócios</a></h2>
										</div>
										
										<div style="height:283px;">
											<a href="conteudo.php?tit=nova_cultivar_de_uva_para_suco_sera_apresentada_para_tecnicos_de_mato_grosso&id=84872"><div class="imagemHome3" style="background-image:url(imagem.php?w=600&h=400&imagem=n_2111_1634123942.jpg)"></div></a>
											<h6>Fruticultura</h6>
											<h2><a href="conteudo.php?tit=nova_cultivar_de_uva_para_suco_sera_apresentada_para_tecnicos_de_mato_grosso&id=84872" class="link2" title="Nova cultivar de uva para suco será apresentada para técnicos de Mato Grosso">Nova cultivar de uva para suco será apresentada para técnicos de Mato Grosso</a></h2>
										</div>
											
												
										<div style="height:283px;">
											<a href="conteudo.php?tit=sistema_cfm_bulltrade_estreia_com_sucesso_e_leilao_fecha_com_receita_superior_a_r_1,6_milhao_de_faturamento_e_400_touros_comercializados&id=84873"><div class="imagemHome3" style="background-image:url(imagem.php?w=600&h=400&imagem=n_2111_980382622.jpg)"></div></a>
											<h6>Sistema CFM BullTrade</h6>
											<h2><a href="conteudo.php?tit=sistema_cfm_bulltrade_estreia_com_sucesso_e_leilao_fecha_com_receita_superior_a_r_1,6_milhao_de_faturamento_e_400_touros_comercializados&id=84873" class="link2" title="Sistema CFM BullTrade estreia com sucesso e leilão fecha com receita superior a R$ 1,6 milhão de faturamento e 400 touros comercializados">Sistema CFM BullTrade estreia com sucesso e leilão fecha com receita superior a R$ 1,6 milhão de faturamento e 400 touros comercializados</a></h2>
										</div>
											
												
										<div style="height:283px;">
											<a href="conteudo.php?tit=famato_defende_maior_repasse_do_fco_para_cooperativas&id=84874"><div class="imagemHome3" style="background-image:url(imagem.php?w=600&h=400&imagem=n_2111_132830236.jpg)"></div></a>
											<h6>Administração rural</h6>
											<h2><a href="conteudo.php?tit=famato_defende_maior_repasse_do_fco_para_cooperativas&id=84874" class="link2" title="Famato defende maior repasse do FCO para cooperativas">
											Famato defende maior repasse do FCO para cooperativas
											</a>
											</h2>
										</div>
										<div style="height:283px;">
											<a href="conteudo.php?tit=industria_de_mato_grosso_pode_sofrer_com_a_escassez_de_materia-prima_em_2013&id=84871"><div class="imagemHome3" style="background-image:url(imagem.php?w=600&h=400&imagem=n_2111_1332833348.jpg)"></div></a>
											<h6>Agroflorestal</h6>
											<h2><a href="conteudo.php?tit=industria_de_mato_grosso_pode_sofrer_com_a_escassez_de_materia-prima_em_2013&id=84871" class="link2" title="Indústria de Mato Grosso pode sofrer com a escassez de matéria-prima em 2013">
											Indústria de Mato Grosso pode sofrer com a escassez de matéria-prima em 2013</a></h2>
										</div>
									</div>
									<script>
										$(document).ready(function() { 
											$('#cyclenews').cycle({fx:'scrollDown',speed:500, delay:3000,pager:'#navslide'});
										});  
									</script>
								<div class="linha"></div>
									<a href="conteudo.php?tit=apla_e_apex-brasil_assinam_convenio_do_projeto_sugarcane_bioenergy_solution_e_realizam_palestras_no_parque_tecnologico_piracicaba&id=84870">
										<div class="imagemHome2" style="width:300px; background-image:url(imagem.php?w=500&h=300&imagem=n_2111_1525725837.jpg)"></div>
									</a>
									<h6>Projeto Sugarcane Bioenergy</h6>
								<h2>
									<a href="conteudo.php?tit=apla_e_apex-brasil_assinam_convenio_do_projeto_sugarcane_bioenergy_solution_e_realizam_palestras_no_parque_tecnologico_piracicaba&id=84870" class="link2" title="Apla e Apex-Brasil assinam convênio do Projeto Sugarcane Bioenergy Solution e realizam palestras no Parque Tecnológico Piracicaba">
									Apla e Apex-Brasil assinam convênio do Projeto Sugarcane Bioenergy Solution e realizam palestras no Parque Tecnológico Piracicaba
									</a>
								</h2>
							
								<div class="linha"></div>
								
								<div style="text-align:center;">
								 <script type="text/javascript"><!--
									google_ad_client = "pub-8137284570178208";
									/* 300x250, Inicial */
									google_ad_slot = "4264054957";
									google_ad_width = 300;
									google_ad_height = 250;
									//-->
									</script>
									<script type="text/javascript"
									src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
									</script>             
								</div>
								<hr />
									<div class="linha2" style="margin-bottom:0"></div>
									<div style="background-color:#F3F3F3; padding:15px 10px 10px 10px; border:1px solid #CCC; border-top:none;">
											<div class="tituloespecial">mais lidas &raquo;</div>
											<br />
											<div class="tituloespecial" style="color:#CCC; font-size:40px; float:left; width:30px; height:30px; line-height:30px">1</div>
											<a href="conteudo.php?tit=safra_201213_seguro_rural_sofre_novo_atraso_de_subvencao&id=84541" class="link2">
											SAFRA 2012/13: Seguro rural sofre novo atraso de subvenção</a>
											<br clear="all" />
											<div style="border-top:1px solid #DDD; height:1px; margin:10px 0;"></div>
											 <div class="tituloespecial" style="color:#CCC; font-size:40px; float:left; width:30px; height:30px; line-height:30px">2</div>
											<a href="conteudo.php?tit=raizen_lanca_campanha_da_promocao_batmovel_shell_v-power&id=84469" class="link2">
											Raízen lança campanha da promoção Batmóvel Shell V-Power</a>
											<br clear="all" />
											<div style="border-top:1px solid #DDD; height:1px; margin:10px 0;"></div>
											<div class="tituloespecial" style="color:#CCC; font-size:40px; float:left; width:30px; height:30px; line-height:30px">3</div>
											<a href="conteudo.php?tit=produtores_de_leite_conhecem_exemplos_de_sistemas_de_producao&id=84390" class="link2">
											Produtores de leite conhecem exemplos de sistemas de produção</a>
											<br clear="all" />
											<div style="border-top:1px solid #DDD; height:1px; margin:10px 0;"></div>
											<div class="tituloespecial" style="color:#CCC; font-size:40px; float:left; width:30px; height:30px; line-height:30px">4</div>
											<a href="conteudo.php?tit=maior_comprador_de_soja_brasileira_amplia_aquisicao_de_produto_em_2012&id=84170" class="link2">
											Maior comprador de soja brasileira amplia aquisição de produto em 2012</a>
											<br clear="all" />
											<div style="border-top:1px solid #DDD; height:1px; margin:10px 0;"></div>
											 <div class="tituloespecial" style="color:#CCC; font-size:40px; float:left; width:30px; height:30px; line-height:30px">5</div>
											<a href="conteudo.php?tit=setor_leiteiro_entrega_lista_com_96_reivindicacoes_ao_governo_federal&id=84358" class="link2">
											Setor leiteiro entrega lista com 96 reivindicações ao governo federal</a>
											<br clear="all" />
									</div>

									<div class="linha"></div>
									<iframe frameborder="0" scrolling="no" height="425" width="490" allowtransparency="true" marginwidth="0" marginheight="0" 
									src="http://comrates.forexpros.com.pt/index.php?pairs_ids=8832;8834;8848;8851;8860;8862;8869;8891;8894;8911;8912;8913;8914;8915;8916;8917;8918;8919;&header-text-color=%23FFFFFF&header-bg=%230c804e&curr-name-color=%230c804e&inner-text-color=%23000000&green-text-color=%232A8215&green-background=%23B7F4C2&red-text-color=%23DC0001&red-background=%23FFE2E2&inner-border-color=%230c804e&border-color=%230c804e&bg1=%23F6F6F6&bg2=%23ffffff&open=hide&last_update=hide">
									</iframe>
									<br />
									<span style="font-size: 11px;color: #333333;text-decoration: none;">
									<a href="http://www.forexpros.com.pt/commodities/" target="_blank" style="font-size: 11px;color: #06529D; font-weight: bold;" class="underline_link">
									Commodities</a> em Tempo Real Oferecidas por Forex Pros – o Portal do Mercado Forex.
									</span>
									<div class="linha2"></div>
						</div>
						
						<div style="float:left; width:168px; margin:0px 6px 0 6px;">
									<div class="tituloespecial shopping"><a href="shopping.php">shopping &raquo;</a></div>
									<br />    
									<a href="conteudo.php?tit=genetica_-_volume_1&id=318">
										<div style="float:left; width:70px; height:100px; margin-right:10px; text-align:center;">
											<img src="imagens/pu_0102_970790029.jpg" width="50px" height="80px" >
										</div>
									</a>
									<div style="float:right; width:88px">
										<h3><a href="produto.php?tit=genetica_-_volume_1&id=318" class="link2">Genética - Volume 1</a></h3>
										<br />
										<strong class="shopping">R$<span style="font-size:26px">55</span>,00</strong>
									</div>
									<br clear="all" /><br />
									<a href="conteudo.php?tit=como_produzir_milho_e_sorgo_para_silagem&id=148">
										<div style="float:left; width:70px; height:100px; margin-right:10px; text-align:center;">
											 <img src="imagens/pu_0102_970790029.jpg" width="50px" height="80px" >
										</div>
									</a>
									<div style="float:right; width:88px">
									<h3><a href="produto.php?tit=como_produzir_milho_e_sorgo_para_silagem&id=148" class="link2">Como Produzir Milho e Sorgo para Silagem</a></h3>
									<br />
										<strong class="shopping">R$<span style="font-size:26px">96</span>,00</strong>
									</div>
									<br clear="all" /><br />
									<a href="conteudo.php?tit=criacao_de_bezerras&id=94">
										<div style="float:left; width:70px; height:100px; margin-right:10px; text-align:center;">
											 <img src="imagens/pu_0102_970790029.jpg" width="50px" height="80px" >
										</div>
									</a>
									<div style="float:right; width:88px">
									<h3><a href="produto.php?tit=criacao_de_bezerras&id=94" class="link2">Criação de Bezerras</a></h3>
									<br />
										<strong class="shopping">R$<span style="font-size:26px">96</span>,00</strong>
									</div>
									<br clear="all" /><br />
									<a href="conteudo.php?tit=teorias_da_demanda_e_do_comportamento_do_consumidor&id=310">
										<div style="float:left; width:70px; height:100px; margin-right:10px; text-align:center;">
											 <img src="imagens/pu_0102_970790029.jpg" width="50px" height="80px" >
										</div>
									</a>
									<div style="float:right; width:88px">
									<h3><a href="produto.php?tit=teorias_da_demanda_e_do_comportamento_do_consumidor&id=310" class="link2">Teorias da Demanda e do Comportamento do Consumidor</a></h3>
									<br />
										<strong class="shopping">R$<span style="font-size:26px">38</span>,00</strong>
									</div>
									<br clear="all" /><br />
									<a href="conteudo.php?tit=fundamentos_do_melhoramento_de_fruteiras&id=581">
									<div style="float:left; width:70px; height:100px; margin-right:10px; text-align:center;">
										 <img src="imagens/pu_0102_970790029.jpg" width="50px" height="80px" >
									</div>
									</a>
									<div style="float:right; width:88px">
										<h3><a href="produto.php?tit=fundamentos_do_melhoramento_de_fruteiras&id=581" class="link2">Fundamentos do Melhoramento de Fruteiras</a></h3>
										<br />
										<strong class="shopping">R$<span style="font-size:26px">45</span>,00</strong>
									</div>
								<br clear="all" /><br />
								
								<div class="linha2"></div>
								<div class="tituloespecial noticias"><a href="conteudos.php?tit=entrevistas&tipo=EN">entrevistas &raquo;</a></div>
								
								<br />
									<h6>14/10 - </h6>
									<h6 style="color:#333; font-weight:bold">Maurício Antônio Lopes</h6>
									<h3 class="noticias"><a href="entrevista.php?tit=novo_presidente_da_embrapa_destaca_a_inteligencia_estrategica&id=156">
									Novo presidente da Embrapa destaca a inteligência estratégica</a></h3>
									<br clear="all" />
									<h6>04/10 - Direito agrário</h6>
									<h6 style="color:#333; font-weight:bold">Patricia Fukuma</h6>
									<h3 class="noticias"><a href="entrevista.php?tit=seguranca_juridica_e_garantia_de_sementes_de_qualidade_para_os_agricultores&id=155">
									Segurança jurídica é garantia de sementes de qualidade para os agricultores</a></h3>
									<br clear="all" />
									<h6>25/09 - </h6>
									<h6 style="color:#333; font-weight:bold">Cléver Pirola Ávila</h6>
									<h3 class="noticias"><a href="entrevista.php?tit=crise_dos_insumos_ameaca_setor_de_suinos_e_aves&id=154">
									Crise dos insumos ameaça setor de suínos e aves</a></h3>
									<br clear="all" />
									<div class="linha2"></div>
									
									<div class="tituloespecial artigos"><a href="conteudos.php?tit=artigos&tipo=A">
									artigos &raquo;</a></div>
									<br />
										<h6>Outros</h6>
										<h3 class="artigos"><a href="conteudo.php?tit=os_graos_integrais_estao_fazendo_bem&id=84315">
										Os grãos integrais estão fazendo bem?
										</a></h3>
										<br clear="all" />
										<h6>Outros</h6>
										<h3 class="artigos"><a href="conteudo.php?tit=o_velho_arroz_com_feijao&id=84002">
										O velho arroz com feijão
										</a></h3>
										<br clear="all" />
										 <h6>Bovinos (corte)</h6>
										<h3 class="artigos"><a href="conteudo.php?tit=o_boi_que_pula_a_porteira_2_parte&id=83854">
										O boi que pula a porteira 2º Parte
										</a></h3>
										<br clear="all" />
						</div>
						<br clear="all" />