        <!-- Dashboard icons -->
            <div class="grid_7">

                <a href="#" class="dashboard-module">
                    <img src="<?php echo $this->baseUrl()?>/images/painel/admin.png" tppabs="<?php echo $this->baseUrl()?>/images/painel/admin.png" width="64" height="64" alt="Sim Imagens" />
                    <span>Administrador</span>
                </a>
                <a href="<?php echo $this->url(array('controller'=>'Artigo','action'=>'index'),null,true);?>" class="dashboard-module">
                    <img src="<?php echo $this->baseUrl()?>/images/painel/artigo.png" tppabs="<?php echo $this->baseUrl()?>/images/painel/artigo.png" width="64" height="64" alt="Sim Imagens" />
                    <span>Artigo</span>
                </a>

                 <a href="<?php echo $this->url(array('controller'=>'Texto','action'=>'index'),null,true);?>" class="dashboard-module">
                    <img src="<?php echo $this->baseUrl()?>/images/painel/texto.png" tppabs="<?php echo $this->baseUrl()?>/images/painel/texto.png" width="64" height="64" alt="Sim Imagens" />
                    <span>Texto</span>
                </a>

                
                <a href="<?php echo $this->url(array('controller'=>'Usuario','action'=>'index'),null,true);?>" class="dashboard-module">
                    <img src="<?php echo $this->baseUrl()?>/images/painel/usuario.gif" tppabs="<?php echo $this->baseUrl()?>/images/painel/usuario.gif" width="64" height="64" alt="Sim Imagens" />
                    <span>Usu&aacute;rio</span>
                </a>
                <a href="<?php echo $this->url(array('controller'=>'Contato','action'=>'Registro'),null,true);?>" class="dashboard-module">
                    <img src="<?php echo $this->baseUrl()?>/images/painel/adduser.png" tppabs="<?php echo $this->baseUrl()?>/images/painel/adduser.png" width="64" height="64" alt="Sim Imagens" />
                    <span>Registro</span>
                </a>
                
                <a href="<?php echo $this->url(array('controller'=>'Noticia','action'=>'index'),null,true);?>" class="dashboard-module">
                    <img src="<?php echo $this->baseUrl()?>/images/painel/news.png" tppabs="<?php echo $this->baseUrl()?>/images/painel/news.png" width="64" height="64" alt="Sim Imagens" />
                    <span>Noticias</span>
                </a>

                <a href="<?php echo $this->url(array('controller'=>'Sobre','action'=>'index'));?>" class="dashboard-module">
                    <img src="<?php echo $this->baseUrl()?>/images/painel/sobre.png" tppabs="<?php echo $this->baseUrl()?>/images/painel/sobre.png" width="64" height="64" alt="Sim Imagens" />
                    <span>Sobre</span>
                </a>
                <a href="<?php echo $this->url(array('controller'=>'Galeria','action'=>'index'),null,true);?>" class="dashboard-module">
                    <img src="<?php echo $this->baseUrl()?>/images/painel/galeria.png" tppabs="<?php echo $this->baseUrl()?>/images/painel/galeria.png" width="64" height="64" alt="Sim Imagens" />
                    <span>Galeria</span>
                </a>
                <a href="<?php echo $this->url(array('controller'=>'Categorianoticia','action'=>'index'),null,true);?>" class="dashboard-module">
                    <img src="<?php echo $this->baseUrl()?>/images/painel/cate_noticia.png" tppabs="<?php echo $this->baseUrl()?>/images/painel/cate_noticia.png" width="64" height="64" alt="Sim Imagens" />
                    <span>Categoria - Noticias</span>
                </a>

                <a href="<?php echo $this->url(array('controller'=>'Categoriapost','action'=>'index'),null,true);?>" class="dashboard-module">
                    <img src="<?php echo $this->baseUrl()?>/images/painel/cate_post.png" tppabs="<?php echo $this->baseUrl()?>/images/painel/cate_post.png" width="64" height="64" alt="Sim Imagens" />
                    <span>Categoria - Post</span>
                </a>

                <a href="<?php echo $this->url(array('controller'=>'Produto','action'=>'menu'),null,true);?>" class="dashboard-module">
                    <img src="<?php echo $this->baseUrl()?>/images/painel/produto.png" tppabs="<?php echo $this->baseUrl()?>/images/painel/produto.png" width="64" height="64" alt="Sim Imagens" />
                    <span>Produto</span>
                </a>
                
                <div style="clear: both"></div>
            </div> <!-- End .grid_7 -->

            <!-- Account overview -->
            <div class="grid_5">
                <div class="module">
                    <h2><span>Usuario Logado</span></h2>
                        <div class="module-body">
                        	<p>
                                <strong>Nome: </strong>
                                <?php echo $this->loggedInAs(); ?>
                                <br />
                                <strong>Você esta logado como:</strong>
                                <?php echo $_SESSION['session_login']['usuario'];?>
                                <br />
                                <strong>Acessar sua conta:</strong>
                                <a href="<?php echo $this->url(array('controller'=>'Usuario'
                                ,'action'=>'Conta'),null,true);?>">click aqui</a>
                                <br />
                                <strong>Visita em :</strong>
                                <?php echo date("d/m/y")  ?>
                                <br />
                                <strong>N&deg; IP :</strong>
                                <?php echo $_SERVER['REMOTE_ADDR']; ?>
                                <br />
                                <strong>Usuario IP :</strong>
                                <?php echo $this->IP; ?>
                                <br />
                            </p>
                            <p>
                                <strong>Para Sair do Sistema:</strong>clique em 
                                <a href="<?php echo $this->url(array('controller'=>'auth'
                                ,'action'=>'logout'),null,true);?>">Sair</a>
                                <br />
                            </p>

                        </div>
                </div>
                <div style="clear:both;"></div>
            </div> <!-- End .grid_5 -->

            <div style="clear:both;"></div>
            <div style="clear:both;"></div>
            <div style="clear:both;"></div>