<div class="editor-toolbar">     
	<div id="toolbar" class="ui-widget-header ui-corner-all">
		<button id="play" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-primary" role="button" title="Pagina Inicial" onclick="linkRedirect('Administrador/menu')">
	       			<span class="ui-button-icon-primary ui-icon fw-button-edit"></span>
	       			<span class="ui-button-text">Inicio</span>
	    </button>	 	
	 	<button id="btnListar" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-primary" role="button" title="Listar" onclick="linkRedirect('Produto/index')"  >
	       			<span class="ui-button-icon-primary ui-icon fw-button-listar"></span>
	       			<span class="ui-button-text">Listar</span>
	    </button>
	</div>
</div>