<div class="grid_12">
    <div class="module">
        <h2><span>Detalhes</span></h2>
        <h1 class="titulo_sohw" >Detalhes</h1>
        <?php if ($this->artigo): ?>
            <dl class="detalhe">
                <dt class="detalhe">ID</dt>
                <dd class="detalhe"><?php echo $this->artigo->id; ?></dd>

                <dt class="detalhe">Titulo</dt>
                <dd class="detalhe"><?php echo $this->artigo->titulo; ?></dd>

                <dt class="detalhe">Comentário</dt>
                <dd class="detalhe"><?php echo $this->artigo->comentario ?></dd>

                <dt class="detalhe">Artigo</dt>
                <dd class="detalhe"><?php echo $this->artigo->noticia ?></dd>

                <dt class="detalhe">Data</dt>
                <dd class="detalhe"><?php echo $this->artigo->data ?></dd>

                <dt class="detalhe">Fonte</dt>
                <dd class="detalhe"><?php echo $this->artigo->fonte ?></dd>

                <dt class="detalhe">Status</dt>
                <dd class="detalhe"><?php echo $this->artigo->ativo ?></dd>
                
                <dt class="detalhe">Foto</dt>
                <dd class="detalhe"><?php echo $this->img($this->baseUrl() . '/upload/artigo/' . $this->artigo->foto, 100, 100, 'sds'); ?></dd>

                <dt class="detalhe">Opciones</dt>
                <dd class="detalhe">
                    <a href="<?php echo $this->url(array('controller' => 'Administrador', 'action' => 'menu'), null, true); ?>">Inicio</a>
                    |
                    <a href="<?php echo $this->url(array('controller' => 'Artigo', 'action' => 'index'), null, true); ?>">Listar Artigos</a>
                    |
                    <?php echo $this->linkvoltar('voltar', 'back', 'volver'); ?>
                </dd>

            </dl>
        <?php else: ?>
            <p><?php echo $this->message ?></p>
        <?php endif ?>
    </div> <!-- End .module -->
    <div style="clear:both;"></div>
</div> <!-- End .grid_12 -->
<div style="clear:both;"></div>