<div class="grid_12">
<!-- Notification boxes -->
<?php echo $this->notificationSucess(); ?>

 <a href="<?php echo $this->url(array('controller'=>'Artigo','action'=>'index'),null,true);?>">Listar Artigo</a>
 |
 <a href="<?php echo $this->url(array('controller'=>'Administrador','action'=>'menu'),null,true);?>">Inicio</a>
</div>

<div style="clear:both;"></div>
<div style="clear:both;"></div>
<div style="clear:both;"></div>