<div class="grid_12">
<!-- Notification boxes -->
<?php echo $this->notificationSucess(); ?>

 <a href="<?php echo $this->url(array('controller'=>'Red','action'=>'index'), null, true);?>">Listar Redes Sociales</a>
 |
 <a href="<?php echo $this->url(array('controller'=>'Administrador','action'=>'menu'), null, true);?>">Inicio</a>
</div>

<div style="clear:both;"></div>
<div style="clear:both;"></div>
<div style="clear:both;"></div>