<div class="grid_12">
<!-- Notification boxes -->
<?php echo $this->notificationSucess(); ?>
 <a href="<?php echo $this->url(array('controller'=>'Administrador','action'=>'menu'), null, true);?>">
 	Inicio
 </a>
 |
 <a href="<?php echo $this->url(array('controller'=>'Categoriapost','action'=>'index'), null, true);?>">
 	Listar Categorias
 </a>
</div>

<div style="clear:both;"></div>
<div style="clear:both;"></div>
<div style="clear:both;"></div>