SELECT * FROM SITE_TEXTO
INSERT INTO `MESTRE`.`SITE_NOTICIAS`
(`TITULO`,
`COMENTARIO`,
`NOTICIA`,
`FOTO`,
`DATA`,
`FONTE`,
`ATIVO`,
`CATEGORIA_NOTICIA_ID`)
VALUES
('',
 '',
 '',
'',
NOW(),
'',
'N',
7
);

/* SELECT * FROM `MESTRE`.`SITE_NOTICIAS` */

/*  INSERT INTO SITE_NOTICIA_MAIS_LIDA(NOTICIA_ID, TITULO)VALUES(4,'T001');     */


/*  SELECT * FROM SITE_NOTICIA_MAIS_LIDA    */

/*  DELETE FROM SITE_NOTICIA_MAIS_LIDA WHERE ID IN (6,7,5)    */

/*  DROP TRIGGER  `MESTRE`.`GERA_CLICK`  */



/*
DELIMITER $$
CREATE TRIGGER `MESTRE`.`GERA_CLICK`
BEFORE INSERT ON `MESTRE`.`SITE_NOTICIA_MAIS_LIDA`
FOR EACH ROW
BEGIN
DECLARE NEWCLICK INT; 
	SELECT 
		COUNT(CLICK) INTO NEWCLICK 
	FROM SITE_NOTICIA_MAIS_LIDA 
	WHERE NOTICIA_ID = NEW.NOTICIA_ID ORDER BY CLICK DESC LIMIT 1;
	IF  NEWCLICK > 0 THEN
       SET NEW.CLICK = NEWCLICK +1 ;
     ELSE
       SET NEW.CLICK = 1;
     END IF;
END$$ */

