<?php echo $this->partial('comun/msg_construcao.phtml'); ?> 
<?php echo $this->render('comun/menu_principal.phtml') ?>

<div id='wrapper'>
    <?php echo $this->partial('comun/menu_banner.phtml'); ?>	
    <div id='red-bg'><!--Begin red-bg box -->   
       <!--black content box -->
       <div id='top-box'></div>
       <div id='middle-box'><!--Begin middle-box box -->  
            <!--Begin carrucel slidorion -->
            <div id="slidorion">
           <div id="slider">
             <div id="slide1" class="slide">
               <img src='<?php echo $this->baseUrl() ?>/images/home/dj2.jpg' width="488" height="400" />
                 </div>
                   <div id="slide2" class="slide">
                     <img src='<?php echo $this->baseUrl() ?>/images/home/dj1.jpg' width="488" height="400" />
                      </div>
                      <div id="slide3" class="slide">
                    <img src='<?php echo $this->baseUrl() ?>/images/home/logo.jpg' width="488" height="400" />
                   </div>
                 <div id="slide4" class="slide">
                <img src='<?php echo $this->baseUrl() ?>/images/home/punto.jpg' width="488" height="400" />
              </div>
            </div>
           <div id="accordion"><!--Begin  accordion -->
                <div class="link-header">Dj N&ordm; 1</div>
                <div class="link-content">
                    <p>Lorem Ipsum</p>
                    <p>has been the industry's standard dummy text ever since the 1500s, when an
                        unknown printer took a galley of type and scrambled it to
                        make a type specimen book. It has survived not only five centuries,
                        but also the leap into electronic typesetting, remaining essentially
                        unchanged. It was popularised in the 1960s with the release of Letraset</p>

                </div>
                <div class="link-header">Dj N&ordm; 2</div>
                <div class="link-content">
                    <p>Dave Lizewski is an unnoticed high school student and comic book fan with a few friends and who lives alone with his father. His life is not very difficult and his personal trials not that overwhelming.</p>
                    <p>However, one day he makes the simple decision to become a super-hero even though he has no powers or training.</p>
                </div>
                <div class="link-header">Dj N&ordm; 3</div>
                <div class="link-content">
                    <p>Lorem Ipsum</p>
                    <p>has been the industry's standard dummy text ever since the 1500s, when an
                        unknown printer took a galley of type and scrambled it to
                        make a type specimen book. It has survived not only five centuries,
                        but also the leap into electronic typesetting, remaining essentially
                        unchanged. It was popularised in the 1960s with the release of Letraset</p>
                </div>
                <div class="link-header">Punto Jovem</div>
                <div class="link-content">
                    <p>Lorem Ipsum</p>
                    <p>has been the industry's standard dummy text ever since the 1500s, when an
                        unknown printer took a galley of type and scrambled it to
                        make a type specimen book. It has survived not only five centuries,
                        but also the leap into electronic typesetting, remaining essentially
                        unchanged. It was popularised in the 1960s with the release of Letraset</p>
                </div>
            </div><!--End  accordion -->
         </div> <!--End  carrucel slidorion -->  
            <div id="spacer"></div>
            <div id="spacer"></div>
            <!-- welcome -->
            <div id='welcome'>
            <div id='photo7'>
                <img alt="" src="<?php echo $this->baseUrl() ?>/images/home/photo5.jpg"/>
            </div>
            <div class='title'>BIENVENIDO</div>
            <div>
                <h2>Contato</h2>
                <?php foreach ($this->dados AS $key => $contato): ?>
                <?php echo $contato['nome'] ?>
                <div id="spacer"></div>
                <?php echo $contato['endereco'] ?>
                <div id="spacer"></div>
                <?php echo $contato['email'] ?>
                <div id="spacer"></div>
                <?php echo $contato['telefone'] ?>
                <div id="spacer"></div>
                <?php echo $contato['celular'] ?>
                <?php endforeach; ?>
            </div>
                <div class='more-btn'>
                    <a class="button-link" href="#">ver m&aacute;s</a>
                </div>
           </div><!--End  welcome -->    
            <!-- eventos -->
            <div id='news'>
                <div class='title'>EVENTOS</div>
               <?php foreach ($this->dadoe AS $key => $eventos): ?>
                <div style="margin-bottom:10px;">
                     <?php echo $eventos['body'] ?>
                </div>
                <div class='sub-title'>
                     <?php echo $eventos['start'] ?>
                </div>
                <div id="spacer"></div>
                     <a style='text-decoration:none; color:#a51313;' href="<?php echo $this->url(array('controller' => 'Evento', 'action' => 'ver', 'id' => $eventos['id']), null , true); ?>">ver m&aacute;s</a>
                <div id="spacer"></div>
                 <?php endforeach; ?>
                 <div class='more-btn'>
                  <a class="button-link" href="<?php echo $this->url(array('controller' => 'Evento', 'action' => 'eventos'), null , true); ?>">
                     Enventos
                  </a>
                </div>
            </div><!--End  news eventos -->
         
            <!-- otros dj´s -->
            <div id='djs'><!--Begin  djs Otros Dj´s -->
             <div class='title'>OTROS DJS</div>
              <div style="margin-top:30px;">
                <?php foreach ($this->dadosd AS $key => $deajay): ?>
                  <div class='dj-img'>
                     <!-- <img alt="" src="<?php echo $this->baseUrl() ?>/css/home/dj/photo2.jpg"/> -->
                       <?php echo $this->img($this->baseUrl() . '/upload/' . $deajay['foto'], 72, 100, 'sds'); ?>
                        </div>
                          <div class='dj-txt'>
                            <div class='sub-title2'>
                             <?php echo $deajay['nome'] ?>
                               </div>
                                <div>
                               <?php echo $deajay['celular'] ?>
                             </div>
                           </div>
                         <div style="clear:both;"></div>
                       <div style="clear:both;"></div>
                     <br/>
                  <?php endforeach; ?>
                <div style="clear:both;"></div>
              <div style="clear:both;"></div>
             </div>
            <div class='more-btn' style="margin-top:40px;">
           <a class="button-link" href="#">ver m&aacute;s</a>
          </div>
         </div><!--End Otros Dj´s -->
       <div style="clear:both;"></div>
     </div><!--End middle-box box -->  
    </div><!--Begin red-bg box -->  