<h2>Edit form in expanded row details</h2>  
	    <div class="demo-info" style="margin-bottom:10px">  
	        <div class="demo-tip icon-tip">&nbsp;</div>  
	        <div>Click the expand button to expand a detail form.</div>  
	    </div>  
      
      
	    <table id="dg" title="Lista de Categorias de Noticias" style="width:700px;height:550px"  
	            url="http://localhost/agronegocio/public/Categoria/getservico"  
	            toolbar="#toolbar" pagination="true"  fitColumns="true" singleSelect="true">  
	        <thead>  
	            <tr>  
	                <th field="id" width="20">ID</th>  
	                <th field="descricao" width="90">Descrição</th>  
	            </tr>  
	        </thead>  
	    </table>  
    <div id="toolbar">  
        <a href="javascript:void(0)" class="easyui-linkbutton" iconCls="icon-add" plain="true" onclick="newItem()">Novo</a>  
        <a href="javascript:void(0)" class="easyui-linkbutton" iconCls="icon-remove" plain="true" onclick="destroyItem()">Destroy</a>  
    </div>  
    <script type="text/javascript">  
        $(function(){  
            $('#dg').datagrid({  
                view: detailview,  
                detailFormatter:function(index,row){  
                    return '<div class="ddv"></div>';  
                },  
                onExpandRow: function(index,row){  
                    var ddv = $(this).datagrid('getRowDetail',index).find('div.ddv');  
                    ddv.panel({  
                        border:false,  
                        cache:true,  
                        href:'http://localhost/agronegocio/public/easyui-form/form_categoria.php?index='+index,  
                        onLoad:function(){  
                            $('#dg').datagrid('fixDetailRowHeight',index);  
                            $('#dg').datagrid('selectRow',index);  
                            $('#dg').datagrid('getRowDetail',index).find('form').form('load',row);  
                        }  
                    });  
                    $('#dg').datagrid('fixDetailRowHeight',index);  
                }  
            });  
        });  
        function saveItem(index){  
            var row 	= $('#dg').datagrid('getRows')[index];  
            var add 	= base_url+'Categoria/post/'
            var update 	= base_url+'Categoria/post/'
            var url 	= row.isNewRecord ? 'http://localhost/agronegocio/public/Categoria/post/' : 'update_user.php?id='+row.id; 
            //var url = row.isNewRecord ? 'save_user.php' : 'update_user.php?id='+row.id;   
            $('#dg').datagrid('getRowDetail',index).find('form').form('submit',{  
                url: url,  
                onSubmit: function(){  
                    //return $(this).form('validate');  

                    return false;
                },  
                success: function(data){  
                    data = eval('('+data+')');  
                    data.isNewRecord = false;  
                    $('#dg').datagrid('collapseRow',index);  
                    $('#dg').datagrid('updateRow',{  
                        index: index,  
                        row: data  
                    });  
                }  
            });  
        }  
        function cancelItem(index){  
            var row = $('#dg').datagrid('getRows')[index];  
            if (row.isNewRecord){  
                $('#dg').datagrid('deleteRow',index);  
            } else {  
                $('#dg').datagrid('collapseRow',index);  
            }  
        }  
        function destroyItem(){  
            var row = $('#dg').datagrid('getSelected');  
            if (row){  
                $.messager.confirm('Confirm','Are you sure you want to remove this user?',function(r){  
                    if (r){  
                        var index = $('#dg').datagrid('getRowIndex',row);  
                        $.post('destroy_user.php',{id:row.id},function(){  
                            $('#dg').datagrid('deleteRow',index);  
                        });  
                    }  
                });  
            }  
        }  
        function newItem(){  
            $('#dg').datagrid('appendRow',{isNewRecord:true});  
            var index = $('#dg').datagrid('getRows').length - 1;  
            $('#dg').datagrid('expandRow', index);  
            $('#dg').datagrid('selectRow', index);  
        }  
    </script>  
    <style type="text/css">  
        form{  
            margin:0;  
            padding:0;  
        }  
        .dv-table td{  
            border:0;  
        }  
        .dv-table input{  
            border:1px solid #ccc;  
        }  
    </style>  