	<div id="texto"><!-- Begin texto -->
		
		<?php //foreach ($this->agricultura AS $key => $item): ?>

		<h1 style="padding:10px 0; color:#000000">O que é?</h1>
		 <p style="text-align: justify"><b>O Conceito</b></p>
		 <p style="text-align: justify"><b>O Conceito</b></p>
		 <p style="text-align: justify">O conceito de "agribusiness" foi proposto pela primeira vez em 1957, por Davis e Goldberg, como a soma das operações de produção e distribuição de suprimentos agrícolas, processamentos e distribuição dos produtos agrícolas&nbsp; e itens produzidos a partir deles.<br>
		<br>
		Assim, de acordo com o conceito de agronegócio, a agricultura passa a&nbsp;ser abordada de maneira associada aos outros agentes responsáveis&nbsp; por todas as atividades, que garantem a produção, transformação, distribuição e consumo de alimentos, considerando assim, a agricultura como parte&nbsp; de uma extensa rede de agentes ecômicos.<br>
		<br>
		Com este conceito formalizado por tais autores, a visão sistêmica passa a ganhar&nbsp; importância, abrangendo todos os envolvidos, desde a pesquisa até o cosumidor final, desde o que comumente se chama&nbsp;"antes da porteira" até "pós-porteira".<br>
		<br>
		As exportações do agronegócio em 2007, segundo dados do&nbsp;Ministério da Agricultura, Pecuária e Abastecimento,&nbsp;totalizaram US$ 58,415 bilhões, um recorde histórico para o setor. Em relação a 2006, as exportações apresentaram um aumento de US$ 8,992 bilhões, o que significou uma taxa de crescimento de 18,2%. <br>
		<br>
		Com isso, as exportações do agronegócio corresponderam a 36,4% das exportações totais brasileiras no período, que foram de US$ 160 bilhões. As importações apresentaram variação anual de 30,2%, totalizando US$ 8,719 bilhões.</p>

	</div>	