<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">  
<html>  
<head>  
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">  
    <meta name="keywords" content="jquery,ui,easy,easyui,web">  
    <meta name="description" content="easyui help you build your web page easily!">  
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<meta name="title" content="Portal do Agronegócio" />
	<meta name="author" content="Desenvolvimento: Axel Alexander" />
	<meta name="reply-to" content="fred@portaldoagronegocio.com.br" />
	<title>Portal do Agroneg&oacute;cio - Not&iacute;cias, Eventos, Artigos e tudo sobre o agroneg&oacute;cio brasileiro e mundial</title>

	<base href="http://<?php echo $_SERVER['HTTP_HOST'] . $this->baseUrl()?>/" />	
	<link href="http://<?php echo $_SERVER['HTTP_HOST'] . $this->baseUrl()?>/images/icon/agro.png" type="image/png" rel="shortcut icon" />

	<link rev="made" href="mailto:axelpatton@gmail.com" /> 
	
	<link rel="stylesheet" href="http://<?php echo $_SERVER['HTTP_HOST'].$this->baseUrl()?>/css/reset.css" type="text/css" />

    <link rel="stylesheet" type="text/css" href="http://<?php echo $_SERVER['HTTP_HOST'] . $this->baseUrl()?>/easyui/themes/default/easyui.css">  
    <link rel="stylesheet" type="text/css" href="http://<?php echo $_SERVER['HTTP_HOST'] . $this->baseUrl()?>/easyui/themes/icon.css">  
    <link rel="stylesheet" type="text/css" href="http://<?php echo $_SERVER['HTTP_HOST'] . $this->baseUrl()?>/easyui/demo/demo.css">  
    <script src="http://<?php echo $_SERVER['HTTP_HOST'] . $this->baseUrl()?>/jquery/jquery-1.6.min.js" type="text/javascript"></script>
	<script type="text/javascript" src="http://<?php echo $_SERVER['HTTP_HOST'] . $this->baseUrl()?>/easyui/jquery.easyui.min.js"></script>  
	
	<script type="text/javascript" src="http://<?php echo $_SERVER['HTTP_HOST'] . $this->baseUrl()?>/easyui/datagrid-detailview.js"></script>

	<script type="text/javascript" src="http://<?php echo $_SERVER['HTTP_HOST'] . $this->baseUrl()?>/easyui/locale/easyui-lang-pt_BR.js"></script>
    <script>
	$(document).ready(function() {
	
     //atualizar = window.setTimeout(function(){window.location.reload()}, 300000);


	});
    </script>



</head>  
<body>  
    
    <!-- zend redirenct--> 
	<?php echo $this->layout()->content?>

</body>  
</html>  