<?php
//$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=ISO-8859-1');
//$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8');
//$this->headTitle()->setSeparator(' - ');
//$this->headTitle('Administração DjDiDiMix :: Regsitrar ');
echo $this->doctype();
?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<link href="http://<?php echo $_SERVER['HTTP_HOST'] . $this->baseUrl()?>/images/icon/lp_16.png" type="image/png" rel="shortcut icon" />
<?php 
$this->headLink()->headLink( array('rel' => 'favicon','href' => $this->baseUrl('images/icon/phppg.png'),'PREPEND') ); 
$this->headLink()->prependStylesheet($this->baseUrl().'/ui-themes/prata/jquery.ui.all.css');
$this->headLink()->prependStylesheet($this->baseUrl().'/css/theme-blue.css');
$this->headLink()->prependStylesheet($this->baseUrl().'/css/thickbox.css');
$this->headLink()->prependStylesheet($this->baseUrl().'/css/tablesorter.css');
$this->headLink()->prependStylesheet($this->baseUrl().'/css/styles.css');
$this->headLink()->prependStylesheet($this->baseUrl().'/css/grid.css');
$this->headLink()->prependStylesheet($this->baseUrl().'/css/reset.css');
$this->headLink()->prependStylesheet($this->baseUrl('/css/ui.jqgrid.css'));

// jquery - jqgrid - jquery ui javascript
$this->headScript()->appendFile($this->baseUrl().'/js/app_site.js');

$this->headScript()->appendFile($this->baseUrl().'/js/funcoes/Funcoes.js');
$this->headScript()->appendFile($this->baseUrl().'/js/funcoes/jqUI.FuncoesMensagens.js');
$this->headScript()->appendFile($this->baseUrl().'/jquery/jquery-1.7.2.js');
$this->headScript()->appendFile($this->baseUrl().'/jquery-ui/jquery-ui-1.8.11.custom.js');
$this->headScript()->appendFile($this->baseUrl().'/jquery/jquery.jplayer.min.js');
$this->headScript()->appendFile($this->baseUrl().'/jquery/jquery.maskedinput-1.3.js');
$this->headScript()->appendFile($this->baseUrl().'/jquery/thickbox.js');
$this->headScript()->appendFile($this->baseUrl().'/jquery/jquery.pstrength-min.1.2.js');
$this->headScript()->appendFile($this->baseUrl().'/jquery/jquery.tablesorter.pager.js');
$this->headScript()->appendFile($this->baseUrl().'/jquery/jquery.tablesorter.min.js');
$this->headScript()->appendFile($this->baseUrl().'/ckeditor/ckeditor.js');
$this->headScript()->appendFile($this->baseUrl().'/ckeditor/sample.js');
$this->headScript()->appendFile($this->baseUrl().'/js/app_jquery.js');
$this->headScript()->appendFile($this->baseUrl('/jqGrid/src/i18n/grid.locale-es.js')) ; 
$this->headScript()->appendFile($this->baseUrl('/jqGrid/jquery.jqGrid.src.js'));
$this->headScript()->appendFile($this->baseUrl('/jqGrid/json2.js'));


$this->headScript()->appendFile($this->baseUrl().'/js/app_jquery.js');
?>
<?php echo  $this->headMeta()     . "\n"; ?>
<?php echo  $this->headTitle()    . "\n"; ?>
<?php echo  "<!-- CSS SITE -->"   . "\n"; ?>
<?php echo  $this->headLink()     . "\n"; ?>
<?php //echo  "<!-- Jquery -->"   . "\n"; ?>
<?php //echo  $this->jQuery() . "\n"; ?>
<?php echo  "<!-- JAVASCRIPT -->" . "\n"; ?>
<?php echo  $this->headScript()   . "\n"; ?>



<!-- Initiate password strength script -->

	</head>
	<body>
    	<!-- Header -->
        <div id="header">
            <!-- Header. Status part -->
            <div id="header-status">
                <div class="container_12">
                    <div class="grid_8">
					&nbsp;
                    </div>
                    <div class="grid_4">
                        <a href="<?php echo $this->baseUrl() ?>/auth/logout" id="logout">
                        Logout
                        </a>
                    </div>
                </div>
                <div style="clear:both;"></div>
            </div> <!-- End #header-status -->

            <!-- Header. Main part -->
            <div id="header-main">
                <div class="container_12">
                    <div class="grid_12">
                        <div id="logo">
                            <ul id="nav">
                                <li id="current"><a href="<?php echo $this->url(array('controller'=>'administrador','action'=>'menu'),null,true);?>">Home</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'Evento','action'=>'index'),null,true);?>">Eventos</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'Deejay','action'=>'index'),null,true);?>">Deejay</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'Usuario','action'=>'index'),null,true);?>">Usu&aacute;rio</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'Galeria','action'=>'index'),null,true);?>">Galeria</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'Categoria','action'=>'index'),null,true);?>">Categoria</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'Musica','action'=>'index'),null,true);?>">Musica</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'Servico','action'=>'index'));?>">Servicios</a></li>
                            </ul>
                        </div><!-- End. #Logo -->
                    </div><!-- End. .grid_12-->
                    <div style="clear: both;"></div>
                </div><!-- End. .container_12 -->
            </div> <!-- End #header-main -->
            <div style="clear: both;"></div>
            <!-- Sub navigation -->
            <div id="subnav">
                <div class="container_12">
                    <div class="grid_12">
                        <ul>
                            <li><a href="<?php echo $this->url(array('controller'=>'Administrador','action'=>'menu'));?>">Inicio</a></li>
                            <li><a href="<?php echo $this->url(array('controller'=>'Artigo','action'=>'index'));?>">Artigo</a></li>

                            <li><a href="<?php echo $this->url(array('controller'=>'Evento','action'=>'index'));?>">Eventos</a></li>
                            <li><a href="<?php echo $this->url(array('controller'=>'Deejay','action'=>'index'));?>">Deejay</a></li>
                           
                            <li><a href="<?php echo $this->url(array('controller'=>'Galeria','action'=>'index'));?>">Galeria</a></li>
                            <li><a href="<?php echo $this->url(array('controller'=>'Categoria','action'=>'index'));?>">Categoria</a></li>
                            <li><a href="<?php echo $this->url(array('controller'=>'Musica','action'=>'index'));?>">M&uacute;sica</a></li>
                            <li><a href="<?php echo $this->url(array('controller'=>'Red','action'=>'index'));?>">Redes Sociales</a></li>
                            <li><a href="<?php echo $this->url(array('controller'=>'Servico','action'=>'index'));?>">Servicios</a></li>
                            <li><a href="<?php echo $this->url(array('controller'=>'Texto','action'=>'index'));?>">Texto</a></li>
                            <li><a href="<?php echo $this->url(array('controller'=>'Usuario','action'=>'index'));?>">Usu&aacute;rio</a></li>
                            <li><a href="<?php echo $this->baseUrl() ?>/auth/logout">Salir</a></li>
                        </ul>

                    </div><!-- End. .grid_12-->
                </div><!-- End. .container_12 -->
                <div style="clear: both;"></div>
            </div> <!-- End #subnav -->
        </div> <!-- End #header -->
        <div class="container_12">
             <?php echo $this->layout()->content?>
        </div> <!-- End .container_12 -->
        <!-- Footer -->
        <div id="footer">
        	<div class="container_12">
            	<div class="grid_12">
                	<!-- You can change the copyright line for your own -->
                	<p>&copy; 2012 DJDiDiMix. todos los Derechos Reservados.
                            Designed By: <a href="#" title="Visite mi pagina en la web">Axel Alexander</a></p>
                </div>
            </div>
            <div style="clear:both;"></div>
        </div> <!-- End #footer -->
	</body>
</html>