<?php echo $this->doctype('XHTML1_TRANSITIONAL')?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>DjDiDiMix :: Punto Jovem ::</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
<!--    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1" /> -->
<base href="http://<?php echo $_SERVER['HTTP_HOST'] . $this->baseUrl()?>/" />	
<link href="http://<?php echo $_SERVER['HTTP_HOST'] . $this->baseUrl()?>/images/icon/lp_16.png" type="image/png" rel="shortcut icon" />
<?php $this->headLink()->prependStylesheet($this->baseUrl().'/ui-themes/prata/jquery.ui.all.css');?>
<?php $this->headLink()->prependStylesheet($this->baseUrl().'/css/style-dj.css');?>
<?php $this->headLink()->prependStylesheet($this->baseUrl().'/css/formulario.css');?>
<?php $this->headLink()->prependStylesheet($this->baseUrl().'/css/skin/jplayer.blue.monday.css');?>
<?php $this->headLink()->prependStylesheet($this->baseUrl().'/css/play-styles.css');?>
<?php $this->headLink()->prependStylesheet($this->baseUrl().'/css/slidorion.css');?>
<?php $this->headLink()->prependStylesheet($this->baseUrl().'/css/menu-mega.css');?> 
<?php $this->headLink()->prependStylesheet($this->baseUrl().'/ui-themes/rlightbox/css/rcarousel.css');?>

<?php $this->headScript()->appendFile($this->baseUrl().'/js/app_site.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl().'/js/Funcoes.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl().'/js/jqUI.FuncoesMensagens.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl().'/jquery/jquery-1.7.2.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl().'/jquery-ui/jquery-ui-1.8.11.custom.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl().'/jquery/jquery.jplayer.min.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl().'/jquery/jquery.maskedinput-1.3.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl().'/jquery/jquery.easing.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl().'/jquery/jquery.slidorion.min.js'); ?>
<?php $this->headScript()->appendFile($this->baseUrl().'/js/app_jquery.js'); ?>

<?php echo  "<!-- CSS -->" . "\n"; ?>
<?php echo  $this->headLink()     . "\n"; ?>
<?php echo  "<!-- JAVASCRIPT -->" . "\n"; ?>
<?php echo  $this->headScript()   . "\n"; ?>
</head>

<body>
 <!-- content -->
 <!-- <div id='red-bg'> -->
       <?php echo $this->layout()->content?>
        <div id='bottom-box'>
        <!-- footer -->
	<div id='footer'>
          <div class="footer-left">
          <img alt="" src="<?php echo $this->baseUrl()?>/images/icon/zend.png"/>
          &ensp;
          <a href="https://www.facebook.com/derlis.paredes/">
             <img alt="" src="<?php echo $this->baseUrl()?>/images/icon/fb.png" border="0"/>
          </a>
          &ensp;
          <a href="#">
             <img alt="" src="<?php echo $this->baseUrl()?>/images/icon/twitter_icon.png" border="0"/>
          </a>
          </div>
            <a href="<?php echo $this->url(array('controller'=>'Auth','action'=>'index'));?>"><img alt="" src="<?php echo $this->baseUrl()?>/images/icon/jockey_16.png"/></a>
             &copy; 2012 DJDiDiMix. todos los Derechos Reservados.Designed By:
            <a style='text-decoration:none; color:#ffffff;' href="http://axelalexander.webcindario.com/">Axel Macnamara</a>
        </div>
        </div>
        <div id='bottom-background'></div>
       
    </div>
</body>
</html>
