<?php echo $this->inlineScript()->appendFile($this->baseUrl('/js/aplication/texto/Texto.js')) ; ?>
<div class="grid_12">
  <div class="module">
      <h2><span>Formulario</span></h2>
      <?php echo $this->form->setAction($this->url()); ?>
      <div class="module-body">
         <p>
           <?php echo $this->img( $this->baseUrl().'/upload/texto/'.$this->form->foto->getValue() ,100,100,'DJ'); ?>
        </p>
      </div>
    </div> <!-- End .module -->

    <div style="clear:both;"></div>
</div> <!-- End .grid_12 -->
<div style="clear:both;"></div>
