<?php $this->headTitle('Login'); ?>

<!-- Account overview -->
            <div class="grid_6"><!-- Begin box grid_6 - informaçoes --> 
                <div class="module">
                    <h2><span>Informa&ccedil;&ocirc;es</span></h2>

                        <div class="module-body">
                            <p>
                                <strong>Usuario deve ser informado:</strong>User X<br />
                                <strong>A Senha deve ser informado: </strong>XXXXX<br />
                                <strong>Visita em : </strong><?php echo date("d/m/y")  ?><br />
                                <strong>N&deg; IP : </strong><?php echo $_SERVER['REMOTE_ADDR'] ?>
                            </p>
                            <p>&nbsp;&nbsp;</p>

                            <p>
                                duvidas<br />
                                <a href="">click aqui</a><br />
                            </p>

                        </div>
                </div>
                <div style="clear:both;"></div>
            </div> <!-- end box grid_6 - informaçoes -->

            <!-- Password -->
            <div class="grid_6">
                <div class="module">
                     <h2><span>Registrar</span></h2>
                    <?php echo $this->form->setAction($this->url()); ?>
                 </div> <!-- End .module -->
                <div style="clear:both;"></div>
            </div> <!-- End .grid_6 -->
            <div style="clear:both;"></div>


