 
<ul id="menu-mega">
    <li><a href="#" class="drop">Djdidi</a><!-- Begin Home Item -->
     <div class="dropdown_2columns"><!-- Begin 2 columns container -->
        <div class="col_2">
          <h2>Djdidi</h2>
        </div>
         <div class="col_2">
           <p>NO SOMOS LOS MEJORES NI TAMPOCO LOS PEORES SIMPLESMENTE SOMOS DIFERENTES</p> 
           <p>Navegar por Internet es a&uacute;n mejor cuandou utilizes un navegador actualizado,</p> 
           <p>recomendamos que utilize su Browser favorito y actualizado para um rendimiento mejorado</p>             
         </div>
         <div class="col_2">
             <h2>Cross Browser Support</h2>
         </div>
         <div class="col_1">
            <img src="<?php echo $this->baseUrl()?>/images/home/browsers.png" width="125" height="48" alt="" />
         </div>
         <div class="col_1">
            <p>Esta web ha sido probado en todos los principales navegadores..</p>
         </div>
        </div><!-- End 2 columns container -->
    </li><!-- End Djdidi Item -->

    <li><a href="#" class="drop">Destaque de Eventos</a><!-- Begin Destaque de Dj Item -->
       <div class="dropdown_5columns"><!-- Begin dropdown_5columns container -->
       
            <div class="col_5">
                <h2>Eventos en destaques</h2>
            </div>
            <?php foreach ($this->dadoe AS $key => $eventos): ?>
            <div class="col_1">
                <p class="black_box"><?php echo utf8_encode ( $eventos['title']) ?></p>
                <p class="italic"> Dia: <?php echo $eventos['start'] ?>.</p>
            </div>
            
           <?php endforeach; ?> 
           <!-- 
           <div class="col_1">
                <p class="italic">This is a sample of an italic text. Consequat scelerisque. Fusce sed lectus at arcu mollis accumsan at nec nisi porta quis sit amet.</p>
            </div>
            <div class="col_1">
                <p class="strong">This is a sample of a bold text. Aliquam sodales nisi nec felis hendrerit ac eleifend lectus feugiat scelerisque.</p>
            </div>-->
            <div class="col_5">
                <h2>Espacio publicitario</h2>
            </div>
           <div class="col_3">
                <img src="<?php echo $this->baseUrl()?>/images/home/01.jpg" width="70" height="70" class="img_left imgshadow" alt="" />
                <p>Eespacio publicitario - Publicaciones - Haga clic aqu&iacute; para ver com puedes tener tu espacio publicitario en nestra pagina web
                     <a href="<?php echo $this->url(array('controller'=>'Contato','action'=>'index'));?>">Tu espacio aquaqu&iacute;...</a>
                </p>     
                <img src="<?php echo $this->baseUrl()?>/images/home/02.jpg" width="70" height="70" class="img_left imgshadow" alt="" />
                <p>Espacio Publicitario - Publicaciones - Haga clic aqu&iacute; para ver com puedes tener tu espacio publicitario en nestra pagina web
                    <a href="<?php echo $this->url(array('controller'=>'Contato','action'=>'index'));?>">Tu espacio aquaqu&iacute;...</a>
                </p>
            </div>
            <div class="col_2">
               <p class="black_box">
                   Todos los eventos  est&aacute;n sujetos a alteraciones de datos y dias publicaci&oacute;nes
               </p>
            </div>
        </div><!-- End 5 columns container -->
    </li><!-- End 5 columns Item -->

    <li><a href="#" class="drop">Patrocinadores</a><!-- Begin Patrocinadores Item -->
    
        <div class="dropdown_4columns"><!-- Begin 4 columns container -->
        
            <div class="col_4">
                <h2>Espacio para Patrocinadores</h2>
            </div>
            <div class="col_1">
              <h3>Patrocinio 1 </h3>
                <ul>
                    <li><a href="#">Patrocinio 1</a></li>
                    <li><a href="#">Patrocinio 2</a></li>
                    <li><a href="#">Patrocinio 3</a></li>
                    <li><a href="#">Patrocinio 4</a></li>
                    <li><a href="#">Patrocinio 5</a></li>
                </ul>   
                 
            </div>
    
            <div class="col_1">
               <h3>Patrocinio 2 </h3>
                <ul>
                    <li><a href="#">Patrocinio 1</a></li>
                    <li><a href="#">Patrocinio 2</a></li>
                    <li><a href="#">Patrocinio 3</a></li>
                    <li><a href="#">Patrocinio 4</a></li>
                    <li><a href="#">Patrocinio 5</a></li>
                </ul>   
                 
            </div>
    
            <div class="col_1">
              <h3>Patrocinio 3 </h3>
                <ul>
                    <li><a href="#">Patrocinio 1</a></li>
                    <li><a href="#">Patrocinio 2</a></li>
                    <li><a href="#">Patrocinio 3</a></li>
                    <li><a href="#">Patrocinio 4</a></li>
                    <li><a href="#">Patrocinio 5</a></li>
                </ul>   
                 
            </div>
    
            <div class="col_1">
                <h3>Patrocinio - Misc</h3>
                <ul>
                    <li><a href="#">Patrocinio 1</a></li>
                    <li><a href="#">Patrocinio 2</a></li>
                    <li><a href="#">Patrocinio 3</a></li>
                    <li><a href="#">Patrocinio 4</a></li>
                    <li><a href="#">Patrocinio 5</a></li>
                    <li><a href="#">More...</a></li>
                </ul>   
            </div>
        </div><!-- End 4 columns container -->
    
    </li><!-- End Menu Principal Item -->
    <li class="menu_right"><a href="#" class="drop">Menu Principal</a>
          <div class="dropdown_1column align_right">
            <div class="col_1">
              <ul class="simple">
                        <li><a href="<?php echo $this->url(array('controller'=>'Index','action'=>'index'), null, true);?>">Inicio</a></li>
                        <li><a href="<?php echo $this->url(array('controller'=>'Auth','action'=>'index'), null, true);?>">Administrador</a></li>
                        <li><a href="<?php echo $this->url(array('controller'=>'Agenda','action'=>'agendar'), null, true);?>">Agenda</a></li>
                        <li><a href="<?php echo $this->url(array('controller'=>'Contato','action'=>'index'), null, true);?>">Contato</a></li>
                        <li><a href="<?php echo $this->url(array('controller'=>'Evento','action'=>'listar'), null, true);?>">Eventos</a></li>
                        <li><a href="<?php echo $this->url(array('controller'=>'Musica','action'=>'player'), null, true);?>">Musicas</a></li>
                        <li><a href="<?php echo $this->url(array('controller'=>'Categoria','action'=>'categorias'), null, true);?>">Galeria</a></li>
                        <li><a href="<?php echo $this->url(array('controller'=>'Sobre','action'=>'sobre'), null, true);?>">Sobre</a></li>
                        <li><a href="<?php echo $this->url(array('controller'=>'Contato','action'=>'registro'), null, true);?>">Registro</a></li>
                        <li><a href="#">Mas...</a></li>
               </ul>   
            </div>
          </div>        
   </li>
   <li class="menu_right"><a href="#" class="drop">Red social</a><!-- Begin Red social Item -->
        <div class="dropdown_3columns align_right"><!-- Begin Red social container -->
            <div class="col_3">
               <h2>Link</h2>
            </div>
            <?php foreach ($this->dado_red AS $key => $red): ?> 
            <div class="col_1">
              <ul class="greybox">
                <li><a href="<?php echo $red['link'] ?>"><?php echo $red['rotulo'] ?></a></li>
              </ul>   
           </div>
            <?php endforeach; ?> 
            <div class="col_3">
               <h2>Espacio publicitario</h2>
            </div>
            <div class="col_3">
             <img src="<?php echo $this->baseUrl()?>/images/home/02.jpg" width="70" height="70" class="img_left imgshadow" alt="" />
              <p>Espacio Publicitario - Publicaciones - Haga clic aqu&iacute; para ver com puedes tener tu espacio publicitario en nestra pagina web
                 <a href="<?php echo $this->url(array('controller'=>'Contato','action'=>'index'));?>">Tu espacio aquaqu&iacute;...</a>
             </p>
            </div>
        </div><!-- End Red social container -->
      </li><!-- End Red social Item -->
</ul>