<?php echo $this->inlineScript()->appendFile($this->baseUrl('/js/aplication/index.js')) ; ?>
<div id='DgMsg'>
    <h1>ESTA P&Aacute;GINA EST&Aacute; BAJO CONSTRUCCI&Oacute;N. </h1>
    <p>Disculpe el inconveniente. Para mayor informaci&oacuten sobre los
        contenidos de la p&aacute;gina que requiri&oacute; por
        favor contactarse a la direcci&oacuten siguiente:
    </p>

    <div id="djs">
        <p class="dj-txt">
            <span class="nome-djs">Derlis Paredes</span> derlis@dididjmix.com
        </p>
    </div>
    <div id="djs">
        <p class="dj-txt">
            <span class="nome-djs">Cleber Lugo</span> cleberlugo@dididjmix.com
        </p>
    </div>
</div>