<div id="Janela_dialog3" title="Servicios para Eventos">
	<div id="tab_info">
		<ul id="ul_tabs">
			<li><a href="#tenant_details">My Tenant</a></li>
			<li><a href="#tenant_events">Events</a></li>
			<li><a href="#tenant_jobs">Jobs</a></li>
			<li id="ui-tab-dialog-close"></li>
		</ul>
		<div id="tab_content">
			<div id="tenant_details">
				some details
			</div>
			<div id="tenant_events">
				some events
			</div>
			<div id="tenant_jobs">
				some jobs
			</div>
		</div>
	</div>
</div>