    <!-- Dashboard icons -->
        <div class="grid_7">
                <a href="<?php echo $this->url(array('controller'=>'Produto','action'=>'index'),null,true);?>" class="dashboard-module">
                    <img src="<?php echo $this->baseUrl()?>/images/painel/produto.png" tppabs="<?php echo $this->baseUrl()?>/images/painel/produto.png" width="64" height="64" alt="Sim Imagens" />
                    <span>Produto</span>
                </a>

                <a href="#" class="dashboard-module">
                    <img src="<?php echo $this->baseUrl()?>/images/painel/grupo.png" tppabs="<?php echo $this->baseUrl()?>/images/painel/grupo.png" width="64" height="64" alt="Sim Imagens" />
                    <span>Produto/Grupo</span>
                </a>
                <a href="<?php echo $this->url(array('controller'=>'Artigo','action'=>'index'),null,true);?>" class="dashboard-module">
                    <img src="<?php echo $this->baseUrl()?>/images/painel/marca.png" tppabs="<?php echo $this->baseUrl()?>/images/painel/marca.png" width="64" height="64" alt="Sim Imagens" />
                    <span>Produto/Marca</span>
                </a>
                <a href="<?php echo $this->url(array('controller'=>'Texto','action'=>'index'),null,true);?>" class="dashboard-module">
                    <img src="<?php echo $this->baseUrl()?>/images/painel/modelo.png" tppabs="<?php echo $this->baseUrl()?>/images/painel/modelo.png" width="64" height="64" alt="Sim Imagens" />
                    <span>Produto/Modelo</span>
                </a>
                <a href="<?php echo $this->url(array('controller'=>'Usuario','action'=>'index'),null,true);?>" class="dashboard-module">
                    <img src="<?php echo $this->baseUrl()?>/images/painel/unidade.png" tppabs="<?php echo $this->baseUrl()?>/images/painel/unidade.png" width="64" height="64" alt="Sim Imagens" />
                    <span>Produto/Unidade</span>
                </a>
                <a href="<?php echo $this->url(array('controller'=>'Contato','action'=>'Registro'),null,true);?>" class="dashboard-module">
                    <img src="<?php echo $this->baseUrl()?>/images/painel/ncm.png" tppabs="<?php echo $this->baseUrl()?>/images/painel/ncm.png" width="64" height="64" alt="Sim Imagens" />
                    <span>Nomenclatura Comum do Mercosul</span>
                </a>
                
                <a href="<?php echo $this->url(array('controller'=>'Noticia','action'=>'index'),null,true);?>" class="dashboard-module">
                    <img src="<?php echo $this->baseUrl()?>/images/painel/ipi.png" tppabs="<?php echo $this->baseUrl()?>/images/painel/ipi.png" width="64" height="64" alt="Sim Imagens" />
                    <span>Imposto sobre Produtos Industrializados</span>
                </a>

                <a href="<?php echo $this->url(array('controller'=>'Sobre','action'=>'index'));?>" class="dashboard-module">
                    <img src="<?php echo $this->baseUrl()?>/images/painel/cor.png" tppabs="<?php echo $this->baseUrl()?>/images/painel/cor.png" width="64" height="64" alt="Sim Imagens" />
                    <span>Produto/Cor</span>
                </a>
            <div style="clear: both"></div>
        </div> <!-- End .grid_7 -->
    <div style="clear:both;"></div>
    <div style="clear:both;"></div>
    <div style="clear:both;"></div>